### ISSUE TITLE
Screenshots of the extension in action

### ISSUE THREAD

**Issue by MadLittleMods** [Glancify/Glancify#72]
Can you share some screenshots of this extension?

I want to see it without having to install

**Comment by simsausaurabh** [comment]
@MadLittleMods I have updated the README.md with snapshots, still here are some of them:

![screenshot from 2018-11-08 13-04-51](https://user-images.githubusercontent.com/16608864/48184618-974f8b80-e358-11e8-88ab-30168ba13075.png)

![screenshot from 2018-11-08 13-06-07](https://user-images.githubusercontent.com/16608864/48184626-9cacd600-e358-11e8-8f9d-fdff480ef243.png)

![screenshot from 2018-11-08 13-13-03](https://user-images.githubusercontent.com/16608864/48184630-9e769980-e358-11e8-80d1-6a3672fe3880.png)

Since Twitter has updated its structure of html page, that's why there are no notifications visible under Twitter Card because the scrapping file of our project is not changed yet.

**Comment by MadLittleMods** [comment]
Thanks for the screenshots and updating the readme!
